version: "3.1"

# This file defines the containers that Docker will use and the respective values for them

services:
  db: # The postgres container
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGES_USER_FILE=/run/secrets/SECRET_POSTGRES_USER
      - POSTGRES_PASSWORD_FILE=/run/secrets/SECRET_POSTGRES_PASS
      - POSTGRES_DB=dbautoscheduler
    secrets:
      - SECRET_POSTGRES_USER
      - SECRET_POSTGRES_PASS

  web: # The Django container, which connects to the db container and runs our tests
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    container_name: autoscheduler
    secrets:
      - SECRET_DJANGO_KEY
      - SECRET_POSTGRES_USER
      - SECRET_POSTGRES_PASS

  # These two containers are for running scrape_courses on a schedule in Compute Engine
  cloud-sql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.11
    # The 0.0.0.0 is key to having this work on Compute Engine
    command: /cloud_sql_proxy -instances=$GCP_DB_NAME=tcp:0.0.0.0:3306
    ports:
      - 3306:3006

  scrape-courses:
    build:
      context: .
      dockerfile: docker/scrape-courses/Dockerfile
    depends_on:
      - cloud-sql-proxy
    volumes:
      - .:/code
    container_name: scrape-courses
    secrets:
      - SECRET_DJANGO_KEY
      - SECRET_POSTGRES_USER
      - SECRET_POSTGRES_PASS

  cloud-sql-proxy-cred-file:
    build:
      # Have to do a custom dockerfile (rather than using image: like cloud-sql-proxy coes)
      # b/c we need to set a context so we can access client-secret.json
      context: ./docker/cloud-sql-proxy-cred-file/
    command: /cloud_sql_proxy -instances=$GCP_DB_NAME=tcp:0.0.0.0:3306 -credential_file=client-secret.json
    # Name it cloud-sql-proxy we can connect it to it as the database IP (rather than connecting to cloud-sql-proxy-cred-file)
    container_name: cloud-sql-proxy
    ports:
      - 3306:3006

  run-migrations:
    build:
      context: .
      dockerfile:  docker/run-migrations/Dockerfile
    depends_on:
      - cloud-sql-proxy-cred-file
    volumes:
      - .:/code
    container_name: run-migrations
    secrets:
      - SECRET_DJANGO_KEY
      - SECRET_POSTGRES_USER
      - SECRET_POSTGRES_PASS

volumes:
  pgdata:

# These are needed for creating the PostgresQL server/database from scratch
secrets:
  SECRET_DJANGO_KEY:
    file: ./config/django_key
  SECRET_POSTGRES_USER:
    file: ./config/postgres_username
  SECRET_POSTGRES_PASS:
    file: ./config/postgres_password
